import pandas as pd
import json
from pathlib import Path
from flask import Flask, render_template, request
import pandas as pd
import plotly.graph_objs as go
from plotly.subplots import make_subplots
import plotly.io as pio
import os

app = Flask(__name__)

def export_static_html(excel_path="excel_chart_web/2025.xlsx", out_path="docs/index.html"):
    # Load & prepare data
    df = pd.read_excel(excel_path)

    # Clean/prepare columns
    df["date_clean"] = pd.to_datetime(df["date_clean"], errors="coerce").dt.date
    df = df.dropna(subset=["price", "date_clean"])
    df["price"] = df["price"] / 1_000_000  # to million ₮

    # Keep only fields we need on the client
    # Rename year col to 'year' for simplicity in JS
    df = df.rename(columns={"Үйлдвэрлэсэн он:": "year"})
    df = df[["date_clean", "price", "title", "year"]].dropna(subset=["title", "year"])

    # Convert for JSON (dates to ISO strings)
    records = [
        {
            "date": str(row["date_clean"]),     # 'YYYY-MM-DD'
            "price": float(row["price"]),
            "title": str(row["title"]),
            "year": int(row["year"]),
        }
        for _, row in df.iterrows()
    ]

    titles = sorted({r["title"] for r in records})
    years = sorted({r["year"] for r in records})

    DATA_JSON = json.dumps(records, ensure_ascii=False)
    TITLES_JSON = json.dumps(titles, ensure_ascii=False)
    YEARS_JSON = json.dumps(years, ensure_ascii=False)

    # Fully static HTML (no Jinja). JS does filtering + plotting.
    html = f"""<!DOCTYPE html>
<html lang="mn">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Chart Viewer</title>
  <script src="https://cdn.plot.ly/plotly-2.35.2.min.js"></script>
  <style>
    body {{ font-family: system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif; margin: 24px; }}
    h1 {{ margin-bottom: 8px; }}
    .controls {{ display: flex; gap: 12px; flex-wrap: wrap; align-items: center; margin: 16px 0 24px; }}
    label {{ font-weight: 600; margin-right: 6px; }}
    select, button {{ padding: 6px 10px; border-radius: 8px; border: 1px solid #ccc; }}
    #chart {{ width: 100%; max-width: 1200px; height: 600px; }}
    .note {{ color: #666; font-size: 12px; margin-top: 8px; }}
  </style>
</head>
<body>
  <h1>СУУДЛЫН АВТО МАШИНЫ ҮНЭ</h1>

  <div class="controls">
    <div>
      <label for="title">Title:</label>
      <select id="title">
        <option value="">-- All --</option>
      </select>
    </div>

    <div>
      <label for="year">Үйлдвэрлэсэн он:</label>
      <select id="year">
        <option value="">-- All --</option>
      </select>
    </div>

    <button id="reset">Reset</button>
  </div>

  <div id="chart"></div>
  <div class="note">Үнэ: медиан (сая ₮). Шугамууд нь 7/30 хоногийн гөлгөр дундаж.</div>

  <script>
    // ---- Embedded data (generated by Python) ----
    const DATA = {DATA_JSON};
    const TITLES = {TITLES_JSON};
    const YEARS = {YEARS_JSON};

    // ---- Populate dropdowns ----
    const titleSelect = document.getElementById('title');
    const yearSelect = document.getElementById('year');

    function populateOptions() {{
      TITLES.forEach(t => {{
        const opt = document.createElement('option');
        opt.value = t; opt.textContent = t;
        titleSelect.appendChild(opt);
      }});
      YEARS.forEach(y => {{
        const opt = document.createElement('option');
        opt.value = y; opt.textContent = y;
        yearSelect.appendChild(opt);
      }});
    }}

    // ---- Helpers ----
    function median(values) {{
      if (!values.length) return null;
      const arr = [...values].sort((a,b) => a-b);
      const mid = Math.floor(arr.length / 2);
      return arr.length % 2 ? arr[mid] : (arr[mid - 1] + arr[mid]) / 2;
    }}

    function rollingMean(arr, window) {{
      const out = new Array(arr.length).fill(null);
      let sum = 0, queue = [];
      for (let i = 0; i < arr.length; i++) {{
        const v = arr[i];
        queue.push(v);
        sum += v;
        if (queue.length > window) sum -= queue.shift();
        if (queue.length === window) out[i] = sum / window;
      }}
      return out;
    }}

    function groupByDate(rows) {{
      // {{date => [prices], count}}
      const map = new Map();
      for (const r of rows) {{
        const d = r.date;
        if (!map.has(d)) map.set(d, []);
        map.get(d).push(r.price);
      }}
      const dates = Array.from(map.keys()).sort();
      const dailyPrice = dates.map(d => median(map.get(d)));
      const counts = dates.map(d => map.get(d).length);
      return {{ dates, dailyPrice, counts }};
    }}

    function filterData() {{
      const tVal = titleSelect.value.trim().toLowerCase();
      const yVal = yearSelect.value;
      return DATA.filter(r => {{
        const passTitle = tVal ? (r.title || '').toLowerCase().includes(tVal) : true;
        const passYear = yVal ? String(r.year) === String(yVal) : true;
        return passTitle && passYear;
      }});
    }}

    function render() {{
      const filtered = filterData();
      const {{ dates, dailyPrice, counts }} = groupByDate(filtered);

      // rolling 7 / 30 based on daily median series
      const r7 = rollingMean(dailyPrice, 7);
      const r30 = rollingMean(dailyPrice, 30);

      const traces = [
        {{
          x: dates, y: dailyPrice, mode: 'markers', name: 'Тухайн өдөр',
          marker: {{ size: 6 }}
        }},
        {{
          x: dates, y: r7, mode: 'lines', name: 'Сүүлийн 7 хоног',
          line: {{ width: 2 }}
        }},
        {{
          x: dates, y: r30, mode: 'lines', name: 'Сүүлийн 30 хоног',
          line: {{ width: 2, dash: 'dot' }}
        }},
        {{
          x: dates, y: counts, type: 'bar', name: 'Зарын тоо', opacity: 0.6,
          yaxis: 'y2'
        }}
      ];

      const layout = {{
        title: '🚗 Машины үнэ (медиан сая.₮)',
        hovermode: 'x unified',
        height: 600,
        template: 'simple_white',
        legend: {{ orientation: 'h', y: -0.25 }},
        yaxis: {{ title: 'сая төгрөг' }},
        yaxis2: {{ title: 'Зарын тоо', overlaying: 'y', side: 'right' }},
        margin: {{ t: 60, r: 60, b: 60, l: 60 }}
      }};

      Plotly.react('chart', traces, layout, {{responsive: true}});
    }}

    // ---- Wire up ----
    populateOptions();
    titleSelect.addEventListener('change', render);
    yearSelect.addEventListener('change', render);
    document.getElementById('reset').addEventListener('click', () => {{
      titleSelect.value = '';
      yearSelect.value = '';
      render();
    }});

    // Initial render
    render();
  </script>
</body>
</html>
"""
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    Path(out_path).write_text(html, encoding="utf-8")
    print(f"✅ Static file written to {out_path}")
